param(
    [Parameter(Mandatory=$true)]
    [string]$OutputFile,

    [Parameter(Mandatory=$true)]
    [string]$Version
)

$ErrorActionPreference = 'Stop'

function Get-BerlinTimeZone {
    try {
        return [System.TimeZoneInfo]::FindSystemTimeZoneById('Europe/Berlin')
    }
    catch {
        return [System.TimeZoneInfo]::FindSystemTimeZoneById('W. Europe Standard Time')
    }
}

$berlinTimeZone = Get-BerlinTimeZone
$buildNow = [System.TimeZoneInfo]::ConvertTime([System.DateTimeOffset]::UtcNow, $berlinTimeZone)
$invariantCulture = [System.Globalization.CultureInfo]::InvariantCulture

$buildDate = $buildNow.ToString('dd.MM.yyyy', $invariantCulture)
$buildTime = $buildNow.ToString('HH:mm:ss', $invariantCulture)
$buildTimestamp = $buildNow.ToString('yyMMdd.HHmmss', $invariantCulture)
$buildVersion = "$Version.$buildTimestamp"

$content = @"
// <auto-generated/>
namespace TestVosk;

public static class BuildInfo
{
    public const string BuildDate = "$buildDate";
    public const string BuildTime = "$buildTime";
    public const string BuildVersion = "$buildVersion";
}
"@

$outputDir = Split-Path -Parent $OutputFile
if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutputFile, $content, $utf8NoBom)
Write-Host "BuildInfo generiert: $OutputFile (Version $buildVersion)"
